package ru.yoomoney.tech.grafana.dsl.dashboard

import ru.yoomoney.tech.grafana.dsl.DashboardElement
import ru.yoomoney.tech.grafana.dsl.annotations.Annotations
import ru.yoomoney.tech.grafana.dsl.annotations.AnnotationsBuilder
import ru.yoomoney.tech.grafana.dsl.dashboard.link.DashboardLinks
import ru.yoomoney.tech.grafana.dsl.dashboard.link.DashboardLinksBuilder
import ru.yoomoney.tech.grafana.dsl.generators.PanelLayoutGenerator
import ru.yoomoney.tech.grafana.dsl.generators.SimplePanelLayoutGenerator
import ru.yoomoney.tech.grafana.dsl.panels.Panel
import ru.yoomoney.tech.grafana.dsl.panels.Panels
import ru.yoomoney.tech.grafana.dsl.panels.PanelsBuilder
import ru.yoomoney.tech.grafana.dsl.time.Refresh
import ru.yoomoney.tech.grafana.dsl.time.h
import ru.yoomoney.tech.grafana.dsl.time.now
import ru.yoomoney.tech.grafana.dsl.time.s
import ru.yoomoney.tech.grafana.dsl.variables.Variables
import ru.yoomoney.tech.grafana.dsl.variables.VariablesBuilder

/**
 * Dashboard builder.
 *
 * @property title Dashboard title
 *
 * @author Dmitry Komarov
 * @since 7/21/18
 */
@DashboardElement
class DashboardBuilder(private val title: String) {

    private val panels = mutableListOf<Panel>()

    var timeRange = now - 6.h..now

    var refresh: Refresh = 30.s

    val tags = mutableListOf<String>()

    val variables = VariablesBuilder()

    var uid: String? = null

    var editable: Boolean = true

    private val annotations = AnnotationsBuilder()

    private val links = DashboardLinksBuilder()

    private val panelLayoutGenerator: PanelLayoutGenerator = SimplePanelLayoutGenerator()

    fun panels(build: PanelsBuilder.() -> Unit) {
        val builder = PanelsBuilder(panelLayoutGenerator)
        builder.build()
        panels += builder.panels
    }

    /**
     * Builder for annotations that displayed on graphs.
     *
     * Can be used several times without any overwriting of previous created annotations.
     */
    fun annotations(build: AnnotationsBuilder.() -> Unit) {
        annotations.build()
    }

    /**
     * Builder fot dashboard links which are displayed on top of a dashboard
     */
    fun links(build: DashboardLinksBuilder.() -> Unit) {
        links.build()
    }

    internal fun createDashboard() = Dashboard(
            uid = uid,
            title = title,
            timeRange = timeRange,
            refresh = refresh,
            tags = Tags(tags + "autogenerated"),
            variables = Variables(variables.variables),
            panels = Panels(panels),
            annotations = Annotations(annotations.annotations),
            links = DashboardLinks(links.links),
            editable = editable
    )
}
