package ru.yandex.money.tools.grafana.dsl.dashboard

import ru.yandex.money.tools.grafana.dsl.DashboardElement
import ru.yandex.money.tools.grafana.dsl.datasource.Datasource
import ru.yandex.money.tools.grafana.dsl.datasource.NullDatasource
import ru.yandex.money.tools.grafana.dsl.time.Refresh
import ru.yandex.money.tools.grafana.dsl.time.h
import ru.yandex.money.tools.grafana.dsl.time.now
import ru.yandex.money.tools.grafana.dsl.time.s
import ru.yandex.money.tools.grafana.dsl.panels.PanelsBuilder
import ru.yandex.money.tools.grafana.dsl.panels.Panel
import ru.yandex.money.tools.grafana.dsl.panels.Panels
import ru.yandex.money.tools.grafana.dsl.variables.Variable
import ru.yandex.money.tools.grafana.dsl.variables.VariableBuilder
import ru.yandex.money.tools.grafana.dsl.variables.VariableDelegate
import ru.yandex.money.tools.grafana.dsl.variables.Variables

/**
 * Билдер дэшборда.
 *
 * @property title название будущего дэшборда
 *
 * @author Dmitry Komarov (komarovdmitry@yamoney.ru)
 * @since 7/21/18
 */
@DashboardElement
class DashboardBuilder(private val title: String) {

    private val panels = mutableListOf<Panel>()

    private val variables = mutableListOf<Variable>()

    var timeRange = now - 6.h..now

    var refresh: Refresh = 30.s

    val tags = mutableListOf<String>()

    fun panels(build: PanelsBuilder.() -> Unit) {
        val builder = PanelsBuilder()
        builder.build()
        panels += builder.panels
    }

    /**
     * Строит переменную без источника данных.
     */
    fun variable(build: VariableBuilder.() -> Unit) = variable(NullDatasource, build)

    /**
     * Строит переменную с источником данных.
     */
    fun variable(datasource: Datasource, build: VariableBuilder.() -> Unit): VariableDelegate {
        val builder = VariableBuilder(datasource)
        builder.build()
        return builder.createDelegate(variables)
    }

    internal fun createDashboard() = Dashboard(
            title,
            timeRange,
            refresh,
            Tags(tags + "autogenerated"),
            Variables(variables),
            Panels(panels)
    )
}
