package ru.yandex.money.tools.grafana.dsl.panels

import org.testng.annotations.Test
import ru.yandex.money.tools.grafana.dsl.dashboard
import ru.yandex.money.tools.grafana.dsl.datasource.Zabbix
import ru.yandex.money.tools.grafana.dsl.jsonFile
import ru.yandex.money.tools.grafana.dsl.panels.repeat.Horizontal
import ru.yandex.money.tools.grafana.dsl.shouldEqualToJson
import ru.yandex.money.tools.grafana.dsl.variables.RefreshMode

class SingleStatPanelBuilderTest {

    @Test
    fun `create singlestat with repeat`() {

        // expect
        val minimalDashboard = dashboard("TestAutogenerated") {

            val hosts by variables.query(datasource = Zabbix, query = "Skrat Back.*") {
                regex = ".*acquirer.*"
                refreshMode = RefreshMode.ON_TIME_RANGE_CHANGE
                includeAllValue = true
            }

            panels {
                singleStat(hosts.asVariable()) {
                    bounds = 3 to 3

                    repeat(hosts) {
                        direction = Horizontal(2)
                    }

                    metrics<Zabbix> {
                        textQuery {
                            host = hosts.asVariable()
                            application = "/App acquirer Ping General/"
                            item = "/service version/"
                            group = "/.*/"
                        }
                    }

                    valueMappings<ValueToTextType> {
                        valueToText {
                            "null" to "N/A"
                        }
                    }

                    timerange {
                        hideTimeOverrideInfo = true
                    }
                }
            }
        }

        // that
        minimalDashboard shouldEqualToJson jsonFile("SinglestatBuilderWithRepeat.json")
    }

    @Test
    fun `create singlestat without repeat`() {

        // expect
        val minimalDashboard = dashboard("TestAutogenerated") {

            val hosts by variables.query(datasource = Zabbix, query = "Skrat Back.*") {
                regex = ".*acquirer.*"
                refreshMode = RefreshMode.ON_TIME_RANGE_CHANGE
                includeAllValue = true
            }

            panels {
                singleStat(hosts.asVariable()) {
                    bounds = 3 to 3

                    metrics<Zabbix> {
                        textQuery {
                            host = hosts.asVariable()
                            application = "/App acquirer Ping General/"
                            item = "/service version/"
                            group = "/.*/"
                            useCaptureGroups = true
                        }
                    }

                    valueMappings<ValueToTextType> {
                        valueToText {
                            "null" to "N/A"
                        }
                    }

                    timerange {
                        hideTimeOverrideInfo = true
                    }
                }
            }
        }

        // that
        minimalDashboard shouldEqualToJson jsonFile("SinglestatBuilderWithoutRepeat.json")
    }
}
