package ru.yandex.money.tools.grafana.dsl.panels

import org.testng.annotations.Test
import ru.yandex.money.tools.grafana.dsl.dashboard
import ru.yandex.money.tools.grafana.dsl.datasource.Zabbix
import ru.yandex.money.tools.grafana.dsl.jsonFile
import ru.yandex.money.tools.grafana.dsl.panels.repeat.Horizontal
import ru.yandex.money.tools.grafana.dsl.panels.stat.ColorMode
import ru.yandex.money.tools.grafana.dsl.panels.stat.ThresholdMode
import ru.yandex.money.tools.grafana.dsl.panels.stat.statPanel
import ru.yandex.money.tools.grafana.dsl.shouldEqualToJson
import ru.yandex.money.tools.grafana.dsl.variables.RefreshMode

/**
 * @author Aleksey Matveev
 * @since 03.11.2020
 */

class StatPanelBuilderTest {
    @Test
    fun `create stat with repeat`() {
        val minimalDashboard = dashboard("TestAutogenerated") {
            // given
            val hosts by variables.query(datasource = Zabbix, query = "Skrat Back.*") {
                regex = ".*acquirer.*"
                refreshMode = RefreshMode.ON_TIME_RANGE_CHANGE
                includeAllValue = true
            }

            panels {
                statPanel(hosts.asVariable()) {
                    bounds = 3 to 3

                    repeat(hosts) {
                        direction = Horizontal(2)
                    }

                    metrics<Zabbix> {
                        textQuery {
                            host = hosts.asVariable()
                            application = "Application data"
                            item = "Application dynamic config version"
                            group = "/.*/"
                            textFilter = ".{11}"
                        }
                    }

                    timerange {
                        hideTimeOverrideInfo = true
                    }

                    options {
                        colorMode = ColorMode.BACKGROUND
                    }

                    fieldConfig {
                        thresholds(ThresholdMode.ABSOLUTE) {
                            steps {
                                "0" to Color.RED
                            }
                        }
                        mappings {
                            valueToText {
                                "null" to "N/A"
                            }
                        }
                    }
                }
            }
        }

        // then
        minimalDashboard shouldEqualToJson jsonFile("StatPanelWithRepeat.json")
    }

    @Test
    fun `create stat without repeat`() {
        val minimalDashboard = dashboard("TestAutogenerated") {
            // given
            val hosts by variables.query(datasource = Zabbix, query = "Skrat Back.*") {
                regex = ".*acquirer.*"
                refreshMode = RefreshMode.ON_TIME_RANGE_CHANGE
                includeAllValue = true
            }

            panels {
                statPanel(hosts.asVariable()) {
                    bounds = 3 to 3

                    metrics<Zabbix> {
                        textQuery {
                            host = hosts.asVariable()
                            application = "Application data"
                            item = "Application dynamic config version"
                            group = "/.*/"
                            textFilter = ".{11}"
                        }
                    }

                    timerange {
                        hideTimeOverrideInfo = true
                    }

                    options {
                        colorMode = ColorMode.BACKGROUND
                    }

                    fieldConfig {
                        thresholds(ThresholdMode.ABSOLUTE) {
                            steps {
                                "0" to Color.RED
                            }
                        }
                        mappings {
                            valueToText {
                                "null" to "N/A"
                            }
                        }
                    }
                }
            }
        }

        // then
        minimalDashboard shouldEqualToJson jsonFile("StatPanelWithoutRepeat.json")
    }
}